In [4]:
import numpy as np

a = np.array([87,23,64,96,12])
b = np.array([[12,43,25],[54,31,50]])

# Sorting
c = np.sort(a)              # sorting done in ascending order.
print (c)
print (np.sort(b))          # each row is sorted.

print()

# Searching
print (np.where(a == 12))      # returns index pos. where element is present.
print (np.where(b % 5 == 0))   # In 2-d, returns [row indexes],[element indexes]. here, [0,1],[2,2]


# "np.searchsorted()" offers a fast way to find indices to insert elements in a 'sorted array', ensuring the array’s order is maintained.
# default insertion 'side = left'.
# Syntax: (array, value, side = left or right, sorter=None)
print (np.searchsorted(c,65))
print (np.searchsorted(c,[23,90]))   


# Filtering
# Method 1:
arr = np.array([10,20,30,40])
mask = [True, False, True, False]     # only elements with 'True' position will be printed.
new = arr[mask]
print (new)
print ()

# Method 2:
mask = (b < 55) & (b%5 == 0) 
new = b[mask]        # converts and returns 1-d array containing elements that satisfy the conditions.
print (new)

[12 23 64 87 96]
[[12 25 43]
 [31 50 54]]

(array([4], dtype=int64),)
(array([0, 1], dtype=int64), array([2, 2], dtype=int64))
3
[1 4]
[10 30]

[25 50]
