In [1]:
# Joining
import numpy as np

a = [[23,33,43],[12,22,32]]
b = [[15,25,35],[11,21,31]]
arr1 = np.array(a)
arr2 = np.array(b)

print (a+b)                            # concatenation of lists.
print (np.concatenate([arr1,arr2]))    # concatenation of arrays.

# for horizontal concatenation:
print (np.concatenate([arr1,arr2],axis = 1))

# for vertical concatenation:
print (np.concatenate([arr1,arr2],axis = 0))

[[23, 33, 43], [12, 22, 32], [15, 25, 35], [11, 21, 31]]
[[23 33 43]
 [12 22 32]
 [15 25 35]
 [11 21 31]]
[[23 33 43 15 25 35]
 [12 22 32 11 21 31]]
[[23 33 43]
 [12 22 32]
 [15 25 35]
 [11 21 31]]


In [2]:
# Splitting
import numpy as np

abc = np.array([10,20,30,40,50,60])
pqr = np.array([[15,20,25],[40,45,50]])

# splitting of 1-d array:
print (abc)
print (np.array_split(abc,3))    # split 'abc' array in 3 parts
print (np.array_split(abc,5))

# splitting of 2-d array:
print (pqr)
print (np.array_split(pqr,2))
print (np.array_split(pqr,3))    # given array doesn't have 3 rows and hence it is splitted in 2 rows and an 
                                 # empty row (showing empty list along with its 'shape' & 'dtype')


[10 20 30 40 50 60]
[array([10, 20]), array([30, 40]), array([50, 60])]
[array([10, 20]), array([30]), array([40]), array([50]), array([60])]
[[15 20 25]
 [40 45 50]]
[array([[15, 20, 25]]), array([[40, 45, 50]])]
[array([[15, 20, 25]]), array([[40, 45, 50]]), array([], shape=(0, 3), dtype=int32)]


In [3]:
# Additional example

import numpy as np

array3 = np.array([[[1, 2], [3, 4]], 
                   [[5, 6], [7, 8]]])

array4 = np.array([[[9, 10], [11, 12]], 
                   [[13, 14], [15, 16]]])

# Concatenation along axis 0
result = np.concatenate((array3, array4), axis=0)
print(result.shape)  # Output: (4, 2, 2)   [4 blocks with 2 rows and 2 columns each]
print (result)

# Concatenation along axis 1
result = np.concatenate((array3, array4), axis=1)
print(result.shape)  # Output: (2, 4, 2)
print (result)

# Concatenation along axis 2
result = np.concatenate((array3, array4), axis=2)
print(result.shape)  # Output: (2, 2, 4)
print (result)

(4, 2, 2)
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]
(2, 4, 2)
[[[ 1  2]
  [ 3  4]
  [ 9 10]
  [11 12]]

 [[ 5  6]
  [ 7  8]
  [13 14]
  [15 16]]]
(2, 2, 4)
[[[ 1  2  9 10]
  [ 3  4 11 12]]

 [[ 5  6 13 14]
  [ 7  8 15 16]]]
