In [6]:
import numpy as np

a = [10,20,30,40]
b = [50,60,70,80]
arr1 = np.array(a)
arr2 = np.array(b)
arr3 = np.array([2])

# addition using operation and function
print (arr1 + arr2)
print (np.add(arr1,arr2))

# subtraction using operation and function
print (arr1 - arr2)
print (np.subtract(arr1,arr2))

# multiply using operation and function
print (arr1 * arr2)
print (np.multiply(arr1,arr2))

# division using operation and function
print (arr1 / arr2)
print (np.divide(arr1,arr2))

# other operations:
print (arr1 ** 2)
print (np.power(arr1,arr3))

c = np.sqrt(arr2)
print (c)
print (c.astype(int))

[ 60  80 100 120]
[ 60  80 100 120]
[-40 -40 -40 -40]
[-40 -40 -40 -40]
[ 500 1200 2100 3200]
[ 500 1200 2100 3200]
[0.2        0.33333333 0.42857143 0.5       ]
[0.2        0.33333333 0.42857143 0.5       ]
[ 100  400  900 1600]
[ 100  400  900 1600]
[7.07106781 7.74596669 8.36660027 8.94427191]
[7 7 8 8]
