In [26]:
import numpy as np

a = np.array([10,20,30,40])
b = np.array([[15,23],[44,67],[78,95]])

print (np.append(a,90))              # appending element at the end. Syntax: (array,value)
print (np.append(a,[100,120]))       # appending multiple elements stored in a list.
print (np.append(b,[100,120,156]))   # convert 2-d to 1-d, then append.

print (np.insert(a,2,25))            # insert element at given index position. Syntax: (array,index,value)
print (np.insert(a,[2,4],25))        # inserting same value at multiple indexes.
print (np.insert(b,1,[99,21]))       # convert 2-d to 1-d, then insert.
print ()

# with the help of axes, the dimensions of array are not reduced.
print (np.insert(b,1,[102,105,27],axis = 1))
print (np.insert(b,3,[102,105],axis = 0))
print (np.insert(b,1,[102],axis = 0))           # as each row has 2 columns, so '102' will be in all columns as only 1 value is given.
print (np.insert(b,[0,2],[110,220],axis = 0))   # elements inserted at multiple index positions.

[10 20 30 40 90]
[ 10  20  30  40 100 120]
[ 15  23  44  67  78  95 100 120 156]
[10 20 25 30 40]
[10 20 25 30 40 25]
[15 99 21 23 44 67 78 95]

[[ 15 102  23]
 [ 44 105  67]
 [ 78  27  95]]
[[ 15  23]
 [ 44  67]
 [ 78  95]
 [102 105]]
[[ 15  23]
 [102 102]
 [ 44  67]
 [ 78  95]]
[[110 220]
 [ 15  23]
 [ 44  67]
 [110 220]
 [ 78  95]]


In [38]:
# Removing 
import numpy as np

a = np.array([10,20,30,40])
b = np.array([[15,23],[44,67],[78,95]])

# Syntax: (array,index)
print (np.delete(a,range(1,4)))      # multiple elements are removed using range function.
print (np.delete(b,2))               # convert 2-d to 1-d, then delete.
print (np.delete(b,2,axis = 0))      
print (np.delete(b,0,axis = 1))

[10]
[15 23 67 78 95]
[[15 23]
 [44 67]]
[[23]
 [67]
 [95]]
