In [1]:
import numpy as np

arr = np.array([10,20,30,40])
print (arr)
print (type(arr))

# Multi-dimensional array (Matrix)
multi_arr = np.array([[10,20,30,40],[50,60,70,80],[10,30,50,70]])    # 2d array created
print (multi_arr)
print ("\n")

# Slicing of the array (same as we do in python) 
print (arr[0:3])
print (arr[:2])
print (arr[-4])
print (arr[-3:-1])  
print (arr[1:])
print (arr[::-1])    # reverse of array printed
print ("\n")

# Slicing of multi-dimensional array:
print (multi_arr[0:3,1:4])    # from all 3 elements, slice index 1 to 4 (not included).
print (multi_arr[1:3,3])      # from 2nd and 3rd element, return index 3.
print (multi_arr[1,0:2])      # from 1st element, slice index element from 0:2.

[10 20 30 40]
<class 'numpy.ndarray'>
[[10 20 30 40]
 [50 60 70 80]
 [10 30 50 70]]


[10 20 30]
[10 20]
10
[20 30]
[20 30 40]
[40 30 20 10]


[[20 30 40]
 [60 70 80]
 [30 50 70]]
[80 70]
[50 60]


In [2]:
import numpy as np

# dimensions of array depends on the no. of brackets placed for array.
multi_3d_arr = np.array([[[5,15,25],[25,35,45]],
                        [[2,12,22],[22,32,42]],
                        [[7,17,27],[27,37,47]]])

print (f"The dimension of array is: {multi_3d_arr.ndim}d")   # "name.ndim" is used to tell dimension of array.
print (multi_3d_arr)

print (multi_3d_arr[:2,1,1:3])   # from 0th and 1st index element bundle, pick 1st index element, slice index 1 to 3.
#print (len(multi_3d_arr))

The dimension of array is: 3d
[[[ 5 15 25]
  [25 35 45]]

 [[ 2 12 22]
  [22 32 42]]

 [[ 7 17 27]
  [27 37 47]]]
[[35 45]
 [32 42]]


In [3]:
import numpy as np

arr1 = np.array([[10,20,30,40],[50,60,70,80],[10,30,50,70]])    # 2d array created
print (arr1)

print (np.shape(arr1))       # returns (no. of rows, no. of columns)
print (np.size(arr1))        # returns total no. of elements present in the array.
print (arr1.dtype)           # returns the datatype of array.
print (len(arr1))            # no. of nested values of array.
print (arr1.astype(str))     # convert data type of arr1 to string.
print (arr1.reshape(6,2))    # re-arrange the elements in the 6x2 format. (keep in mind size of array before choosing the format)


[[10 20 30 40]
 [50 60 70 80]
 [10 30 50 70]]
(3, 4)
12
int32
3
[['10' '20' '30' '40']
 ['50' '60' '70' '80']
 ['10' '30' '50' '70']]
[[10 20]
 [30 40]
 [50 60]
 [70 80]
 [10 30]
 [50 70]]
