In [1]:
import numpy as np

# Ways of creating array:
# Conversion from other python structures (eg. list,tuples)
# Intrinsic numpy array creation objects (eg. arange,ones,zeros etc.)
# Reading arrays from disk.
# Use of special library functions (eg. random)

In [2]:
# In 'np.zeros', shape is passed for the array where each element will be 0. (default dtype = float)

zero = np.zeros([2,5])
print (zero)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [3]:
# 'np.arange' works like range function, where elements from 1 to 14 will be present in array.

print (np.arange(1,15))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [4]:
# 'np.linspace' returns (start no., end no., no. of elements present each having equal distance btw them)

print (np.linspace(15,40,5))

[15.   21.25 27.5  33.75 40.  ]


In [5]:
# 'np.empty' returns empty array of given shape with random garbage values assigned by default.

print (np.empty([3,4]))

[[1.54301619e-311 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [1.33511018e-306 5.15059400e-062 1.45098967e+165 1.42134480e+161]
 [1.85586821e-051 8.07452895e+169 3.88886509e-033 3.93284277e-061]]


In [14]:
# 'np.identity(x)' return a identity matrix of x*x shape.

print (np.identity(35))

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [28]:
# reshape to multi-dimensional array and then again converting back to 1-d array.

arr = np.arange(1,51)
print (arr)
print (arr.shape)
print ()
arr = arr.reshape(10,5)
print (arr)
print (arr.shape)
print ()
arr = arr.ravel()      # converts multi-dimensions to 1-d array.
print (arr)
print (arr.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
(50,)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]
(10, 5)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
(50,)


In [34]:
array = np.array([[3,5,7],[6,9,10],[5,2,8]])
print (array)
print ()
print (array.T)   # transpose the array i.e. converts rows into columns and columns into rows.
print ()

[[ 3  5  7]
 [ 6  9 10]
 [ 5  2  8]]

[[ 3  6  5]
 [ 5  9  2]
 [ 7 10  8]]



In [40]:
# '.flat' function is used to convert the array into an iterative array because of which we can use loops.
# It iterates the elements row-wise.

iterate = array.flat
for item in iterate:
    print (item)

3
5
7
6
9
10
5
2
8
