In [1]:
import numpy as np

In [2]:
# mathematical calculations are not performed on list:

l1 = [50,60,70]
l2 = [20,30,40]
l3 = 5
print (l1+l2)        # concatenation is done and not addition.
print (l1*l3)        # multiplied printing of same list is done and not multiplication.

# list can have any no. of elements in their dimensions
l4 = [[10,20,30,40],[23,13]]
print (l4)

[50, 60, 70, 20, 30, 40]
[50, 60, 70, 50, 60, 70, 50, 60, 70, 50, 60, 70, 50, 60, 70]
[[10, 20, 30, 40], [23, 13]]


In [3]:
# for mathematical direct calculations, we use arrays:

l1 = np.array([50,60,70])      # "np.array()" is used to define arrays.
l2 = np.array([20,30,40])
l3 = np.array([5])
print (l1+l2)
print (l1*l3)

[ 70  90 110]
[250 300 350]


In [4]:
# if you keep multiple datatypes in a given array, all elements datatype will be converted.
# for eg: if string datatype is entered, then all int elements will be converted to string.

a = np.array([20,30,"60"])
print (a)

['20' '30' '60']


In [5]:
#a = np.array([[20,30],[40,10,50]])  # won't print bcz both dimensions should have same no. of elements.
a = np.array([[20,30],[40,10]])
print (a)

[[20 30]
 [40 10]]


In [22]:
list1 = [10,20,30,40]
print ("Before conversion: ",list1)
list1 = np.array(list1)               # you can convert list into array in this manner.
print ("After conversiion: ",list1)

print (np.asarray(list1))             # another method to convert list into array using 'np.asarray' function.

Before conversion:  [10, 20, 30, 40]
After conversiion:  [10 20 30 40]
[10 20 30 40]
